name: build
on:
  release:
    types: [created]
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          cache: npm
      - run: npm ci
      - run: npm run test:coverage
      - run: npm run build
      - run: npm publish
        if: github.event_name == 'release' && github.event.action == 'created'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
